/**
 * Demo block — frame mocked as a macOS window. Renders a 12-second
 * Remotion-generated loop showing the ATS analyzer in action.
 *
 * The default `/demo.mp4` is generated by the Remotion `LandingDemo`
 * composition (cf. `remotion/src/compositions/LandingDemo.tsx`). To
 * regenerate after changes:
 *
 *   cd remotion
 *   pnpm exec remotion render LandingDemo out/landing-demo.mp4 --quiet
 *   ffmpeg -i out/landing-demo.mp4 -vf "scale=1920:-2" -an \
 *          -movflags +faststart -c:v libx264 -preset slow -crf 26 \
 *          -pix_fmt yuv420p ../landing/public/demo.mp4
 *
 * Override at deploy-time by setting `VITE_DEMO_VIDEO_URL` to a CDN
 * URL (Cloudflare R2, etc.) once the file outgrows the bundle.
 */

const DEMO_URL = (import.meta.env.VITE_DEMO_VIDEO_URL as string | undefined) ?? "/demo.mp4";

export default function Demo() {
  return (
    <section className="demo">
      <div className="container">
        <div className="demo__frame">
          <div className="demo__chrome" aria-hidden>
            <span className="demo__dot" />
            <span className="demo__dot" />
            <span className="demo__dot" />
            <span className="demo__title">Career OS — Dashboard</span>
          </div>
          <div className="demo__body">
            {DEMO_URL ? (
              <video
                className="demo__video"
                src={DEMO_URL}
                autoPlay
                loop
                muted
                playsInline
                preload="metadata"
              />
            ) : (
              <div className="demo__placeholder">
                <p>Screen recording loop · 12s · 16:10</p>
                <code>landing/public/demo.mp4</code>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
